CREATE  TABLE IF NOT EXISTS calendar (
  id INTEGER  PRIMARY KEY AUTOINCREMENT ,
  data_create DATE not NULL DEFAULT  CURRENT_TIMESTAMP,
  start_data DATE not NULL DEFAULT  CURRENT_TIMESTAMP,
  end_data date not null ,
  STATUS INTEGER CHECK (STATUS =1 or STATUS=0) NOT NULL DEFAULT 1,
  text TEXT NOT NULL DEFAULT '-'
);